version: '3'

services:

  github-release:
    image: 'github-release'
    build: './src'

  www:
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '80:80'

  api:
    container_name: 'api'
    build: './src/api'
    volumes:
      - './src/api:/app'
    ports:
      - '8080:80'

