version: '3'

services:

  www:
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '80:80'

  api:
    build: './src/api'
    volumes:
      - './src/api:/app'
    ports:
      - '8080:80'
