version: '3'

services:

  docker-push:
    image: 'tmvdl/projects:study'
    build: './src/www'

  github-release:
    image: 'github-release'
    build: './src'

  www:
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '80:80'
    depends_on:
      - 'api'

  api:
    container_name: 'api'
    build: './src/api'
    volumes:
      - './src/api:/app'
